# config/packages/sonata_admin.yaml

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Astralib Admin
    dashboard:
        groups:
            default:
                label: Administrator
            debug:
                label: Debugging
                label_catalogue: ~
                items:
                    - route:        app_admin_debug_pdf
                      label:        PDF file
