admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
